### ISSUE TITLE
npm install gives error

### ISSUE THREAD

**Issue by tpm-tli** [dswtpvtltd/reactnativetest#1]
```
> npm install
npm ERR! code ERESOLVE
npm ERR! ERESOLVE unable to resolve dependency tree
npm ERR! 
npm ERR! While resolving: rn_test@0.0.1
npm ERR! Found: react@18.2.0
npm ERR! node_modules/react
npm ERR!   react@"18.2.0" from the root project
npm ERR! 
npm ERR! Could not resolve dependency:
npm ERR! peer react@"^15.5.0" from enzyme-adapter-react-15@1.4.4
npm ERR! node_modules/enzyme-adapter-react-15
npm ERR!   enzyme-adapter-react-15@"^1.4.4" from the root project
npm ERR! 
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.
```

**Comment by dswtpvtltd** [comment]
Sir, please try with yarn. I am not getting these error on yarn

**Comment by dswtpvtltd** [comment]
> > npm install
> npm ERR! code ERESOLVE
> npm ERR! ERESOLVE unable to resolve dependency tree
> npm ERR! 
> npm ERR! While resolving: rn_test@0.0.1
> npm ERR! Found: react@18.2.0
> npm ERR! node_modules/react
> npm ERR!   react@"18.2.0" from the root project
> npm ERR! 
> npm ERR! Could not resolve dependency:
> npm ERR! peer react@"^15.5.0" from enzyme-adapter-react-15@1.4.4
> npm ERR! node_modules/enzyme-adapter-react-15
> npm ERR!   enzyme-adapter-react-15@"^1.4.4" from the root project
> npm ERR! 
> npm ERR! Fix the upstream dependency conflict, or retry
> npm ERR! this command with --force or --legacy-peer-deps
> npm ERR! to accept an incorrect (and potentially broken) dependency resolution.

Sir, please try with yarn. I am not getting these error on yarn
![Screenshot 2023-08-10 at 7 56 59 PM](https://github.com/dswtpvtltd/reactnativetest/assets/3082270/c162a66d-9459-436f-bffa-745f08ac18e1)

**Comment by tpm-tli** [comment]
Yes, `yarn` worked (it complained on dependencies but continued).
Thanks!
